---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/zosmximy/public_html/wp-content/themes/mmoffice/
    - /bin/cp -R * $DEPLOYPATH
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
